### ISSUE TITLE
client: [feature] Support proxy configuration.

### ISSUE THREAD

**Issue by mescalitox** [minio/minio-java#540] opened 2017-04-03 08:41 UTC
add a proxy configuration to the minio client

**Comment by harshavardhana** [comment] 2017-11-21 00:52
https://github.com/MarkusBernhardt/proxy-vole/ - This can be achieved by simply doing 

```java
import com.github.markusbernhardt.proxy.ProxySearch;
import java.net.ProxySelector;

public class XDF {
  public static void main(String[] args) {
    ProxySearch x = ProxySearch.getDefaultProxySearch();
    ProxySelector.setDefault(x.getProxySelector());
  }
}
```

OkHTTP honors this - nothing needs to be done by minio-java end here.

**Comment by nitisht** [comment] 2017-12-01 04:25
@mescalitox closing this as working as intended. Feel free to re-open if there are any issues

**Closed by nitisht** 2017-12-01 04:25 UTC
Labels: priority: low
