### ISSUE TITLE
File breakpoint-upload feature

### ISSUE THREAD

**Issue by LPLambert** [minio/minio-java#822] opened 2019-12-02 08:34 UTC
Our team needs the file breakpoint upload feature.
Now, I've read MinIO's Java API documentation. The putObject function transparently uplows objects larger than 5MiB to multiple parts. However, this feature does not expose the API. So, when the client upload fails, I have to start uploading again.
I would like to provide an API to allow me to continue uploading from the same location when I upload a file again after it fails.

**Comment by harshavardhana** [comment] 2019-12-02 17:35
Unfortunately there is no break point upload feature possible with S3 API

**Comment by kannappanr** [comment] 2019-12-04 00:45
Closing this issue as working as intended. Please feel free to reach out to us at https://slack.min.io for such questions in the future

**Closed by kannappanr** 2019-12-04 00:45 UTC
Labels: community, priority: medium, working as intended
