### ISSUE TITLE
Protocol Exception - Unexpected status line: 0

### ISSUE THREAD

**Issue by martinblaustein** [minio/minio-java#686] opened 2018-07-02 19:25 UTC
Hi,

When trying to perform different operations with the minio Client I get  the following exception
"Protocol Exception - Unexpected status line: 0" from the StatusLine class in okhttp3.internal.http; Bellow is the whole stack.

The same request that sometimes fails other times works just fine, retrying after a fail ussually works.

Is this be a minio issue with the request it's creating?

Exception stack trace:
java.net.ProtocolException: Unexpected status line: 0
	at okhttp3.internal.http.StatusLine.parse(StatusLine.java:69) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[okhttp-3.7.0.jar!/:?]
	at okhttp3.RealCall.execute(RealCall.java:69) ~[okhttp-3.7.0.jar!/:?]
	at io.minio.MinioClient.execute(MinioClient.java:1105) ~[minio-4.0.0.jar!/:4.0.0]
	at io.minio.MinioClient.executeHead(MinioClient.java:1314) ~[minio-4.0.0.jar!/:4.0.0]
	at io.minio.MinioClient.bucketExists(MinioClient.java:3000) ~[minio-4.0.0.jar!/:4.0.0]

**Comment by Praveenrajmani** [comment] 2018-11-02 05:57
looks like the server reponse's status-line is corrupted and not in this particular format `Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF`.  
From the above trace, i can infer that the exception was raised when `bucketExists` was called. Tried reproducing with the same. It doesn't happen now.
Can you check if this still persists ? @martinblaustein

**Comment by martinblaustein** [comment] 2018-11-02 13:08
Hi @Praveenrajmani working on version 4.0 the issue keeps happening. Btw just by adding 1 retry after each request the issue is "solved". 
Updating to the latest version should fix the error completly?

Thanks

**Comment by Praveenrajmani** [comment] 2018-11-02 13:16
> Hi @Praveenrajmani working on version 4.0 the issue keeps happening. Btw just by adding 1 retry after each request the issue is "solved".
> Updating to the latest version should fix the error completly?
> 
> Thanks
Hi @martinblaustein , Which minio ( server ) version are you using ? is the issue happening in ` bucketExists` calls ?
Yes, you can try updating the server version and sdk version also

**Comment by Praveenrajmani** [comment] 2018-11-02 13:17
Hi @martinblaustein , Which minio ( server ) version are you using ? is the issue happening in bucketExists calls ?
Yes, you can try updating the server version and sdk version also

**Comment by martinblaustein** [comment] 2018-11-02 16:08
We are working with 4.0.0 and yes I see the issuie happing on the bucketExists call.

I will try updating the version and see if the issue is solved.

**Comment by deekoder** [comment] 2018-12-04 01:59
@martinblaustein I will close this as not repro. Please reopen this if you still see it.

**Closed** 2018-12-04 01:59 UTC
Labels: community, priority: medium, triage, working as intended
