### ISSUE TITLE
ListObjects example not working with S3

### ISSUE THREAD

**Issue by ehsanwaris** [minio/minio-java#939] opened 2020-05-16 09:56 UTC
Hi, 
I'm trying out the examples and List Objects Example is not working for with S3. 
It is giving me following error.

_Error occurred: org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name="Owner", type=void.class, data=false, required=true) on field 'owner' private io.minio.messages.Owner io.minio.messages.Item.owner for class io.minio.messages.Item at line 2_

**Comment by balamurugana** [comment] 2020-05-16 12:39
Duplicate of https://github.com/minio/minio-java/issues/920.
Fixed by https://github.com/minio/minio-java/pull/921.

**Closed by balamurugana** 2020-05-16 12:39 UTC
