### ISSUE TITLE
Getting.."The difference between the request time and the server's time is too large" while checking if bucket Exists.

### ISSUE THREAD

**Issue by LahariGuntha** [minio/minio-java#701] opened 2018-08-31 14:17 UTC
Hi...
I am trying to clone Bucket ion Minio..

It used to work fine..but all of a sudden started throwing the below error:

My code is of below format:
MinioClient minioClient = new MinioClient("https://play.minio.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG");
        boolean isExist = minioClient.bucketExists("asiatrip");
      if(isExist) {
        System.out.println("Bucket already exists.");
      } else {
        minioClient.makeBucket("asiatrip");
      }
Getting error while checking if bucketExists with below error code:

error occured
--
  | ErrorResponse(code=RequestTimeTooSkewed, message=The difference between the request time and the server's time is too large., bucketName=null, objectName=null, resource=/confpagecr/, requestId=3L137, hostId=3L137)
  | request={method=GET, url=https://play.minio.io:9000/mybucket/?location=, headers=Host: play.minio.io:9000
  | User-Agent: Minio (amd64; amd64) minio-java/dev
  | x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  | x-amz-date: 20180831T130351Z
  | Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20180831/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
  | }
  | response={code=403, headers=Accept-Ranges: bytes
  | Content-Type: application/xml
  | Server: Minio/RELEASE.2018-02-09T22-40-05Z (linux; amd64)
  | Vary: Origin
  | X-Amz-Request-Id: 154FFA9E2A386AFC
  | Date: Fri, 31 Aug 2018 13:19:15 GMT
  | Transfer-Encoding: chunked
  | }

How can we resolve this??Should I set time somewhere??

**Comment by nitisht** [comment] 2018-08-31 14:30
Can you confirm if the time on the client machine is set correctly

**Comment by LahariGuntha** [comment] 2018-08-31 14:59
Hi Nitisht,

We are having Minio as a docker container. We are hitting minio from another application which is also a docker  container. I have checked the time on both the containers. It is same.I did not get what to change because both are having the same time set.

Thanks,
Lahari G

**Comment by nitisht** [comment] 2018-08-31 15:27
well the URL i see in the issue is of our Play server so I got confused.

Can you paste sample code snippet for us to reproduce the issue

**Comment by harshavardhana** [comment] 2018-09-01 09:15
@LahariGuntha setup ntp on client and as well as servers it will work fine.

**Comment by nitisht** [comment] 2018-09-06 03:44
@LahariGuntha were you able to setup ntp on client and server

**Comment by LahariGuntha** [comment] 2018-09-06 10:07
Hi,

Since both the applications are containers..I have checked the time in both the containers. Both are in Sync. 

I have a small query:
According to me:
Client will be the container from which I am accessing Minio and the server will be Minio container 

Is it the same from what you meant by the server and the client??

**Comment by nitisht** [comment] 2018-09-06 10:07
> Client will be the container from which I am accessing Minio and the server will be Minio container

That is correct

**Comment by LahariGuntha** [comment] 2018-09-06 13:49
Hi,
I have checked the time in both the containers. Both are having same time.

**Comment by LahariGuntha** [comment] 2018-09-07 06:05
Hi,

Yeah...My code is referring to Our Minio server only and moreover we are facing this issue intemittently.

**Comment by nitisht** [comment] 2018-09-07 06:15
Can you pls join us on Slack https://slack.minio.io we can check further on possible causes for this

**Comment by nitisht** [comment] 2018-09-13 02:44
@LahariGuntha any progress here?

**Comment by LahariGuntha** [comment] 2018-09-17 07:40
Hi Nitisht,

The Issue we are facing is Intermittent. We did not face this Issue again.

**Comment by nitisht** [comment] 2018-09-17 07:42
okay, thanks. I am closing this issue for now, please feel free to reopen/join us on slack if it happens again.

**Closed by nitisht** 2018-09-17 07:42 UTC
Labels: priority: medium, triage

**Comment by muzammilhussnain14** [comment] 2018-11-27 10:07
@nitisht  I'm using MinIO Java client for uploading files. On Android devices Some time it's common for users to have incorrect time. This shouldn't fail the uploading of file. anyone workaround to solve this issue for users having incorrect time on their android devices ?

**Comment by nitisht** [comment] 2018-11-27 14:51
@muzammilhussnain14 current `timestamp` is a part of S3 signature calculation process (ref: https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) - i.e. server uses current time to validate a REST request sent by the client. If client is using incorrect time (or different time than server) this validation will fail. This is true if you use AWS S3 as well. This is how the S3v4 works and there is not much we can do

note that we do allow 15 mins of skew time, i.e. server and client can be 15 mins apart

**Comment by muzammilhussnain14** [comment] 2018-11-28 05:51
> @muzammilhussnain14 current `timestamp` is a part of S3 signature calculation process (ref: https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) - i.e. server uses current time to validate a REST request sent by the client. If client is using incorrect time (or different time than server) this validation will fail. This is true if you use AWS S3 as well. This is how the S3v4 works and there is not much we can do
> 
> note that we do allow 15 mins of skew time, i.e. server and client can be 15 mins apart

Anyway to  set `x-amz-date` in header instead of device time using Java client ?
