### ISSUE TITLE
Failed to retrieve working download link with minioClient.presignedGetObject

### ISSUE THREAD

**Issue by Makapoh54** [minio/minio-java#485] opened 2016-11-20 13:28 UTC
So. I am trying to upload file from filesystem to minio storage and retrieve link. Using this method I can successfuly upload file and it appears in storage explorer. Retrieved link looks normaly, but it returns such response:
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key/>
<BucketName/>
<Resource>/mosaic/1.png</Resource>
<RequestId>3L137</RequestId>
<HostId>3L137</HostId>
</Error>`

Used method:
 ```
public String uploadFile(String filePath, String bucketName)
    throws NoSuchAlgorithmException, IOException, InvalidKeyException,
    XmlPullParserException {
        try {
      
            MinioClient minioClient = new MinioClient(endpoint,  access_key,
                sectret_key);

            boolean isExist = minioClient.bucketExists(bucketName);
            if (!isExist) {
                minioClient.makeBucket(bucketName);
            }

            File f = new File(filePath);
            minioClient.putObject(bucketName, f.getName(), filePath);
            return minioClient.presignedGetObject(bucketName, f.getName());
        } catch (MinioException e) {

            System.out.println("Error occurred: " + e);
            return e.getMessage();
        }
}
```

I tried also to hardcode minioClient.presignedGetObject(bucketName, f.getName()); this line, but response is the same.

**Comment by balamurugana** [comment] 2016-11-20 19:47
@Makapoh54 I am not able to reproduce this with `play.minio.io` and latest minio master branch.  Could you tell me about your minio server setup info like
* minio version
* minio setup ie whether its FS or XL

**Comment by harshavardhana** [comment] 2016-12-18 11:16
> @Makapoh54 I am not able to reproduce this with play.minio.io and latest minio master branch. Could you tell me about your minio server setup info like
> 
> minio version
> minio setup ie whether its FS or XL

Closing this for now as working as expected  @Makapoh54  - please re-open if seen again.

**Closed by harshavardhana** 2016-12-18 11:16 UTC
