### ISSUE TITLE
Regressions in v.8.5.0, "class file for okhttp3.HttpUrl and com.fasterxml.jackson.databind.JsonMappingException not found".

### ISSUE THREAD

**Issue by LSmyrnaios** [minio/minio-java#1413] opened 2023-01-10 14:31 UTC
Hi, after updating to the new version (8.5.0), my code could not be built.

I get two error messages:

1) ```java: cannot access okhttp3.HttpUrl,  class file for okhttp3.HttpUrl not found```

The link leads to this line in my code:
```minioClient = MinioClient.builder().endpoint(endpoint).credentials(accessKey, secretKey).region(region).build();```

2) ```java: cannot access com.fasterxml.jackson.databind.JsonMappingException,  class file for com.fasterxml.jackson.databind.JsonMappingException not found```

The link leads to this line in my code:
```resultItem.get()```

in which, the "resultItem" is an object of the class `io.minio.Result<io.minio.messages.Item>`, from the minio dependency.
Apparently, this "get()" method may throw the aforementioned exception, which is why it fails to be built.

Please note that these two may not be the only regressions introduced in this update, since some other dependency definitions have changed as well.
Most likely, this bug was introduced in this commit: https://github.com/minio/minio-java/commit/8c7a5be3a42ae0e1f4da9269e97a30729b3cbf83

**Comment by balamurugana** [comment] 2023-01-10 14:34
Duplicate of https://github.com/minio/minio-java/issues/1411

**Comment by balamurugana** [comment] 2023-01-10 14:34
We will be releasing v8.5.1 soon. Stay tuned!

**Closed by balamurugana** 2023-01-10 14:34 UTC

**Comment by LSmyrnaios** [comment] 2023-01-10 14:44
Thank you.

Could you please also update the various dependencies used by minio?
