### ISSUE TITLE
How to support Topic or Cloud Function based notifications.

### ISSUE THREAD

**Issue by songzijiang** [minio/minio-java#712] opened 2018-10-19 05:48 UTC
i'm trying to set the notifications but it gievs me `io.minio.errors.ErrorResponseException: Minio server does not support Topic or Cloud Function based notifications.`what should i do to deal with the problems

**Comment by kannappanr** [comment] 2018-10-19 18:30
This looks like a duplicate of #710

**Comment by songzijiang** [comment] 2018-10-20 02:42
yep,it happend when i new the object.and if i get object from the minioclinet,it throws the exception like #710

**Comment by kannappanr** [comment] 2018-11-01 22:13
closing this issue as duplicate of #710

**Closed by kannappanr** 2018-11-01 22:13 UTC
Labels: community, duplicate, priority: medium

**Comment by kannappanr** [comment] 2018-11-09 18:44
@songzijiang Minio does not support Topic notifications. We will update the example such that you can use it in Minio.
