### ISSUE TITLE
Concurrent Threads to putObject,some threads take about 2.x sec/thread

### ISSUE THREAD

**Issue by liuliliGithub** [minio/minio-java#668] opened 2018-04-01 08:18 UTC
## scene
i want test the speed of concurrent threads's putObject. then i set 20 threads and 100 objects/thread. and the upload time is a bit long. some threads take about 2.x sec, even 3 sec. i found client request not cost long time, but wait response always cost more. and i found the thread dump has more okhttp's connectionPool thread. 
## my code
```java
@Test
    public void stabilityTest3_thread() throws InvalidPortException, InvalidEndpointException, InterruptedException {
        int threadnums =20;
        final int num = 100;
        final int timeout = 2000;
        final String filePath = "C:\\文件.jpg";
        final List<Long> times = new ArrayList<>();
        final CountDownLatch countDownLatch = new CountDownLatch(threadnums);
        AtomicInteger countR = new AtomicInteger(0);
        AtomicInteger countE = new AtomicInteger(0);
        long startTime1 = System.currentTimeMillis();
        for(int i = 0 ;i< threadnums; i++){
            final int index =i;
            new Thread(()->{
                    for(int j = 0; j< num; j++) {
                        long startTime2 = System.currentTimeMillis();
                        try {
                        FileInputStream fileInputStream = new FileInputStream(filePath);
                        MinioClient client1 = new MinioClient("http://ip",port,"accessKey", "secretKey");
                        client1.putObject("zuxp", "test/hello/minio/hei/文件"+(index*100+j)+".jpg",
                                fileInputStream, Files.probeContentType(Paths.get(filePath)));
                        if (fileInputStream != null) {
                            fileInputStream.close();
                        }
                        } catch (Exception e) {
                            e.printStackTrace();
                        } finally{
                            long perTime = System.currentTimeMillis() - startTime2;
                            times.add(perTime);
                            if(perTime < timeout) {
                                countR.addAndGet(1);
                            }else{
                                countE.addAndGet(1);
                                System.out.println("time out per upload time:"+perTime);
                            }
                            
                        }
                    }
                countDownLatch.countDown();
                
            }).start();
        }
        countDownLatch.await();
        Collections.sort(times);
        
        System.out.println(String.format("upload total time:%s,timeout upload num:%s, good upload num:%s,min time:%s, max time:%s",(System.currentTimeMillis()-startTime1),
                 countE.get(), countR.get(), times.get(0), times.get(times.size()-1)));
        
        
    }
```
## result
> set timeout:2000, upload total time:118360,timeout upload num:100, good upload num:1900,min time:278, max time:3012

### client
- java-client:minio-3.0.7.jar
- machine net speed:1000Mb/s
- jdk:1.7
- test pic size: 1.5M
### server
- server-version:2017-11-22T19:55:46Z
- MEMORY
Used: 7.5 MB | Allocated: 3.3 TB | Used-Heap: 7.5 MB | Allocated-Heap: 196 MB
- PLATFORM
Host: localhost.localdomain | OS: linux | Arch: amd64
- RUNTIME
Version: go1.9.1 | CPUs: 4
- machine net speed:1000Mb/s

**Comment by nitisht** [comment] 2018-04-20 05:48
@liuliliGithub I tried reproducing the scenario, and can confirm the behaviour. Here are few observations

> but wait response always cost more. and i found the thread dump has more okhttp's connectionPool thread.

OkHttp [implements blocking APIs](https://github.com/square/okhttp/wiki/Concurrency), so probably there is certain amount of waiting before the connection is being reused. 

Also, I tried using separate files for upload as `FileInputStream fileInputStream = new FileInputStream(filePath);` seems to be bottleneck. That sped up the uploads

```
upload total time:10617,timeout upload num:0, good upload num:2000,min time:16, max time:782
```

**Comment by liuliliGithub** [comment] 2018-04-23 02:52
@nitisht thanks reply
1. i will try test separate files upload speed
2. i will try cofirm how much time taken for reuse connection

**Comment by liuliliGithub** [comment] 2018-05-07 15:38
@nitisht i tried. i create folder and create 1000 files which size about 1.5MB, and i modified code:
```java
    private static ExecutorService executorService = new ThreadPoolExecutor(10, 150,
            60, TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>(), new ThreadPoolExecutor.DiscardOldestPolicy());
    private static final long DEFAULT_CONNECTION_TIMEOUT = 1 * 60;
  private static void test_minio(String fileDir) throws InterruptedException {
       File dirFile = new File(fileDir);
        String[] fileNames = dirFile.list();

        final String endPoint = "endPoint ";
        final String accessKey = "accessKey ";
        final String secretKey = "secretKey“;
        final String bucketName = "test";
        final OkHttpClient httpClient = new OkHttpClient.Builder()
                .connectionPool(new ConnectionPool(10,5*60, TimeUnit.SECONDS))
                .connectTimeout(DEFAULT_CONNECTION_TIMEOUT, TimeUnit.SECONDS)
                .writeTimeout(DEFAULT_CONNECTION_TIMEOUT, TimeUnit.SECONDS)
                .readTimeout(DEFAULT_CONNECTION_TIMEOUT, TimeUnit.SECONDS).build();
        httpClient.dispatcher().setMaxRequestsPerHost(250);
        int num=0;
        final List<Long> totalTimes = new ArrayList<Long>();
        final List<Long> timeoutTimes = new ArrayList<Long>();
        final Long timeout = 1000L;
        long startTime = System.currentTimeMillis();
        final CountDownLatch countDownLatch = new CountDownLatch(fileNames.length);
        for(String fileName : fileNames) {
            num++;
            final File file = new File(fileDir+File.separator+fileName);
            final int finalNum = num;
            executorService.submit(new Runnable() {
                @Override
                public void run() {
                    long start_time = System.currentTimeMillis();
                    try(FileInputStream stream = new FileInputStream(file)){
                        MinioClient minioClient = new MinioClient(endPoint,
                                0, accessKey, secretKey, null, false, httpClient);
                        minioClient.putObject(bucketName, "liulili/"+file.getName(), stream, null);
                    }catch(Exception e) {
                        e.printStackTrace();
                    }
                    long end_time = System.currentTimeMillis();
                    long cost_time = end_time-start_time;
                    totalTimes.add(cost_time);
                    if(cost_time > timeout){
                        System.out.println(String.format("[result]time=%s,num=%s,threadId=%s,path=%s",
                                cost_time, finalNum, Thread.currentThread().getId(), file.getPath()));
                        timeoutTimes.add(cost_time);
                    } else{
                        System.out.println(String.format("[result]time=%s, num=%s,threadId=%s",
                                cost_time, finalNum, Thread.currentThread().getId()));
                    }
                    countDownLatch.countDown();
                }
            });
        }
        countDownLatch.await();
        long endTime = System.currentTimeMillis();
        long totalCostTime = endTime -startTime;
        Collections.sort(totalTimes);
          System.out.println(String.format("upload total time:%s, timeout upload num:%s, good upload num:%s, min time:%s, max time:%s",
                endTime-startTime, timeoutTimes.size(), totalTimes.size()-timeoutTimes.size(), totalTimes.get(0), totalTimes.get(totalTimes.size()-1)));
}
```
and i upload two sences:
1. upload to one minio's node, then 
```
upload total time:36262, timeout upload num:2, good upload num:982, min time:88, max time:1007
```
2. upload to four minio's node, then 
```
upload total time:124108, timeout upload num:781, good upload num:222, min time:115, max time:2954
```

whether it takes longer because of file synchronization between cluster nodes？

**Comment by nitisht** [comment] 2018-05-22 14:11
> whether it takes longer because of object storage blocks synchronization between cluster nodes？

Generally speaking yes, but can you explain the 4 node setup you started ?

**Comment by nitisht** [comment] 2018-06-09 06:18
@liuliliGithub is there anything you want to address here, or we can close this?

**Comment by nitisht** [comment] 2018-06-25 08:14
@liuliliGithub closing due to no response. Feel free to reopen if there are further questions

**Closed by nitisht** 2018-06-25 08:14 UTC
Labels: priority: medium
