### ISSUE TITLE
Japanese Character not supported in User MetaData while saving the object

### ISSUE THREAD

**Issue by Prafulljohri** [minio/minio-java#1124] opened 2020-11-23 09:03 UTC
I'm not able to put Japanese characters in user metadata while putting the Object using the putObject method.

Getting the below exception: 

java.lang.IllegalArgumentException: Unexpected char 0x540d at 11 in header name: x-amz-meta-名前
	at okhttp3.Headers.checkName(Headers.java:273)
	at okhttp3.Headers$Builder.set(Headers.java:414)
	at okhttp3.Request$Builder.header(Request.java:184)

**Comment by balamurugana** [comment] 2020-11-23 10:29
Duplicate of https://github.com/minio/minio-java/issues/1078

Please use the latest release.

**Closed by balamurugana** 2020-11-23 10:29 UTC
