### ISSUE TITLE
Add the ability to add additional upload parameters to a putObject and fPutObject

### ISSUE THREAD

**Issue by PsyTae** [minio/minio-java#530] opened 2017-03-06 18:03 UTC
Our company uses extra parameters when uploading files to the s3 such as the `Metadata: { someKey : 'STRING_VALUE' }` object.  It would be nice to be able to add additional parameters as AWS-SDK does.  as referenced [Here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property).

**Comment by PsyTae** [comment] 2017-03-06 18:07
wrong repository.

**Comment by harshavardhana** [comment] 2017-03-06 18:07
Closing as duplicate of #450

**Closed** 2017-03-06 18:10 UTC
Labels: enhancement
