### ISSUE TITLE
Docker container name as endpoint

### ISSUE THREAD

**Issue by DeepSnowNeeL** [minio/minio-java#702] opened 2018-09-06 23:52 UTC
Cross posting as I have the same issue with the Java library :

"minio_test" doesn't work as endpoint but it resolves thanks to the docker DNS system, please allow for simple name endpoints. I fixed it temporarly by using http://minio_test:9000 as my endpoint

See this for c# lib discussion :
https://github.com/minio/minio-dotnet/issues/238

**Comment by Praveenrajmani** [comment] 2018-11-02 06:20
Yes @DeepSnowNeeL, We need to set the endpoint to `http://minio_test:9000` and `minio_test` resolves from the docker dns registry. What you have done is correct so far

**Comment by deekoder** [comment] 2018-12-04 02:00
Closing this as working as intended. Please reopen if you think this needs to be addressed further.

**Closed by deekoder** 2018-12-04 02:00 UTC
Labels: community, priority: medium, working as intended
