### ISSUE TITLE
Error request on set bucket lifecycle

### ISSUE THREAD

**Issue by victorapa** [minio/minio-java#770] opened 2019-05-02 15:43 UTC
I'm trying to set a bucket lifecycle and always getting the following error:
```
A header you provided implies functionality that is not implemented
error occurred
ErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=null, objectName=null, resource=/container, requestId=null, hostId=null)
request={method=PUT, url=http://localhost:9000/container?lifecycle=, headers=x-amz-meta-Content-Length: 190
Content-MD5: mTEzETzs+QzEEE6Kb1eWFQ==
Host: localhost:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: 98644abdd2540ff56ef1275b3e3ce458acf74012a2756ef4e01e8996019c6a1e
x-amz-date: 20190502T151636Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190502/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-content-length, Signature=*REDACTED*
}
response={code=501, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: MinIO/RELEASE.2019-04-23T23-50-36Z
Date: Thu, 02 May 2019 15:16:36 GMT
Transfer-Encoding: chunked
}
```

My code is the same as the example on Java API reference:
```
    public void setLifeCycle()
            throws InvalidBucketNameException, NoSuchAlgorithmException,
            InsufficientDataException, IOException, InvalidKeyException, NoResponseException,
            XmlPullParserException, ErrorResponseException, InternalException, InvalidArgumentException {
        String lifeCycle = "<LifecycleConfiguration><Rule><ID>expire-bucket</ID><Prefix></Prefix>"
                + "<Status>Enabled</Status><Expiration><Days>365</Days></Expiration>"
                + "</Rule></LifecycleConfiguration>";
        minioClient.setBucketLifeCycle(containerId, lifeCycle);
    }
```

Lifecycles are implemented on Minio exactly like on S3? Or i'm doing something wrong?

**Comment by nitisht** [comment] 2019-05-02 15:50
> Lifecycles are implemented on Minio exactly like on S3? Or i'm doing something wrong?

Lifecycles are currently not supported on MinIO @victorapa . We're working on adding the support. You can follow the progress here: https://github.com/minio/minio/issues/5139

Closing this issue, as working as intended. Feel free to get back if there any further questions..

**Closed by nitisht** 2019-05-02 15:50 UTC

**Comment by victorapa** [comment] 2019-05-02 21:07
Would be interesting to document this on official docs, not?

Thanks for your supporting.

**Comment by harshavardhana** [comment] 2019-05-02 21:08
https://github.com/minio/minio/commit/f40d6e51b92ed255137edaa7c0824a4954f4d840
