### ISSUE TITLE
Mint test 'putObject' fails when Minio runs as s3 gateway

### ISSUE THREAD

**Issue by ebozduman** [minio/minio-java#620] opened 2017-09-30 02:12 UTC
Here is the error log message:
```
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream body, long size, String contentType)",
  "args": "contentType: application/javascript",
  "duration": 1375959,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: timeout >>> [okio.Okio$4.newTimeoutException(Okio.java:227), okio.AsyncTimeout.exit(AsyncTimeout.java:284), okio.AsyncTimeout$2.read(AsyncTimeout.java:240), okio.RealBufferedSource.indexOf(RealBufferedSource.java:344), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210), okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), io.minio.MinioClient.execute(MinioClient.java:1091), io.minio.MinioClient.executePut(MinioClient.java:1359), io.minio.MinioClient.executePut(MinioClient.java:1381), io.minio.MinioClient.putObject(MinioClient.java:3647), io.minio.MinioClient.putObject(MinioClient.java:3757), io.minio.MinioClient.putObject(MinioClient.java:3342), FunctionalTest.testPutObjectUnknownStreamSize(FunctionalTest.java:561), FunctionalTest.putObject_test8(FunctionalTest.java:591), FunctionalTest.runTests(FunctionalTest.java:2349), FunctionalTest.main(FunctionalTest.java:2476)]"
}
```

This could be a regression due to the fix for Issue #615

**Comment by balamurugana** [comment] 2017-09-30 15:27
@ebozduman Please open all mint related issues into `mint` project.

**Comment by balamurugana** [comment] 2017-09-30 15:39
I am not able to reproduce this now.  The exception
```java
java.net.SocketTimeoutException: timeout
    okio.Okio$4.newTimeoutException(Okio.java:227),
    okio.AsyncTimeout.exit(AsyncTimeout.java:284),
    okio.AsyncTimeout$2.read(AsyncTimeout.java:240),
    ...
```
occurred due to slowness of gateway s3 backend response.

**Comment by ebozduman** [comment] 2017-10-04 03:04
I'll try to reproduce it and add my findings here.

**Comment by krisis** [comment] 2017-10-23 19:31
@ebozduman did you get a chance to recreate the issue again?

**Comment by ebozduman** [comment] 2017-10-25 18:40
I tried once with no success.
I wanted to try again if we still have time to try.

Ersan

**Comment by balamurugana** [comment] 2017-10-25 18:52
We can close the issue now and reopen when reproduced.

**Comment by nitisht** [comment] 2017-10-26 04:00
Closing as not reproducible anymore.

**Closed by nitisht** 2017-10-26 04:00 UTC
Labels: priority: medium
